version: "3.8"
services:
  postgres:
    image: postgres:14.0-alpine3.14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 7072:8025
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 7070:8080
      # - 40000:40000 # only valid for debug.Dockerfile
    environment:
      PSI_APP_PORT: 8080
      PSI_BOOTSTRAP_USER: coordinator@psi.com.br|Abc123!@#
      PSI_SITE_URL: http://localhost:7007
      PSI_SMTP_HOST: mailhog
      PSI_SMTP_PORT: 1025
      PSI_SMTP_USERNAME:
      PSI_SMTP_PASSWORD:
      PSI_FILES_BASE_FOLDER: /data/files
      PSI_POSTGRES_DSN: host=postgres user=postgres password=pass dbname=postgres port=5432
    volumes:
      - ./.tmp/files:/data/files
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  jobs:
    build: ./jobs
    environment:
      PSI_BACKEND_URL: http://app:8080/gql
      PSI_JOBRUNNER_USERNAME: jobrunner@psi.com.br
      PSI_JOBRUNNER_PASSWORD: Abc123!@#
      PSI_GET_NEW_TOKEN_FREQUENCY: 10s
      PSI_PROCESS_PENDING_MAIL_FREQUENCY: 10s
      PSI_CREATE_PENDING_APPOINTMENTS_FREQUENCY: 60s
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
