version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./.tmp/mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: on-failure:3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
  app:
    image: golang
    ports:
      - 8082:8082
    environment:
      PSI_MONGO_HOST: mongo
      PSI_MONGO_PORT: 27017
      PSI_MONGO_USERNAME: root
      PSI_MONGO_PASSWORD: pass
      PSI_SMTP_HOST: smtp.ethereal.email
      PSI_SMTP_PORT: 587
      PSI_SMTP_USERNAME: jeffry.hane@ethereal.email
      PSI_SMTP_PASSWORD: A65MQcx1AVgT8gAVFg
    volumes:
      - ~/go:/go
      - .:/app
    working_dir: /app
    command: sh -c "go run github.com/99designs/gqlgen generate && go run main.go"
    depends_on:
      - mongo
