version: "3.8"
services:
  mongo:
    image: mongo:5.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./.tmp/mongodb:/data/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    restart: on-failure:3
    ports:
      - 7071:8081
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 7072:8025
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 7070:8080
      - 40000:40000
    environment:
      PSI_APP_PORT: 8080
      PSI_BOOTSTRAP_USER: coordinator@psi.com.br|Abc123!@#
      PSI_MONGO_URI: mongodb://root:pass@mongo
      PSI_SITE_URL: http://localhost:7007
      PSI_SMTP_HOST: mailhog
      PSI_SMTP_PORT: 1025
      PSI_SMTP_USERNAME:
      PSI_SMTP_PASSWORD:
      PSI_FILES_BASE_FOLDER: /data/files
    volumes:
      - ./.tmp/files:/data/files
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
  jobs:
    build: ./jobs
    environment:
      PSI_BACKEND_URL: http://app:8080/gql
      PSI_JOBRUNNER_USERNAME: jobrunner@psi.com.br
      PSI_JOBRUNNER_PASSWORD: Xyz*()890
      PSI_GET_NEW_TOKEN_FREQUENCY: 10s
      PSI_PROCESS_PENDING_MAIL_FREQUENCY: 10s
      PSI_CREATE_PENDING_APPOINTMENTS_FREQUENCY: 60s
    depends_on:
      - app
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
