FROM golang:1.16rc1-alpine3.12 AS build
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go get github.com/go-delve/delve/cmd/dlv
COPY . .
RUN chmod +x ./build.sh
RUN ./build.sh

FROM alpine:3.12
COPY --from=build /go/bin/dlv /
COPY --from=build /out /
EXPOSE 8080 40000
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/main"]
