version: "3.8"
services:
  mongo:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./.tmp/mongodb:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    restart: on-failure:3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8082:8025
  app:
    build: .
    image: psi-server:0.1.0
    ports:
      - 8080:8080
    environment:
      PSI_BOOTSTRAP_USER: coordinator@psi.com.br|Abc123!@#
      PSI_MONGO_HOST: mongo
      PSI_MONGO_PORT: 27017
      PSI_MONGO_USERNAME: root
      PSI_MONGO_PASSWORD: pass
      PSI_SITE_URL: http://localhost:3000
      PSI_SMTP_HOST: mailhog
      PSI_SMTP_PORT: 1025
      PSI_SMTP_USERNAME:
      PSI_SMTP_PASSWORD:
    depends_on:
      - mongo
  jobs:
    build: ./jobs
    image: psi-jobs:0.1.0
    environment:
      PSI_BACKEND_URL: http://host.docker.internal:8080/gql
      PSI_CONNECT_USER: jobrunner@psi.com.br
      PSI_CONNECT_PASSWORD: Xyz*()890
    depends_on:
      - app
